### ISSUE TITLE
requestPermission not showing any popup nor resolving the promise - swpush

### ISSUE THREAD

**Issue by jishnunbhattathiri** [alcfeoh/ng-weather#2]
Hi, I tried running this code and in my browser (both chrome and firefox latest versions) I am not getting the notification permission popup. push.requestPermssion is hence never resolved and its not sending back the endpoint data. could you please help get it working?

**Comment by alcfeoh** [comment]
Did you use the PWA branch? https://github.com/alcfeoh/ng-weather/tree/pwa Also you'll have to use HTTPS (very likely) for the PWA behavior to work properly.

**Comment by jishnunbhattathiri** [comment]
Yeah I used PWA branch, but haven't tried with https, let me try that. Thank you.

**Comment by jishnunbhattathiri** [comment]
Tried with https as well, but no luck ( infact I tried deploying to a firebase hosting [here](https://pwa-sample-6e674.firebaseapp.com/)).

**Comment by alcfeoh** [comment]
Did you start the local service for notifications on port 9020?

**Comment by jishnunbhattathiri** [comment]
Yes I have. I made a simpler replica of the code [here](https://github.com/jishnunbhattathiri/angular8-pwa-sample) It worked when I served the dist with http-server and used push-server.js for notifications. But still its showing inconsistency. When I unregister service worker and removed the notification permission from chrome, and again visited, its not working, not even sw is registering. 

I have opened an issue in stackoverflow as well [here](https://stackoverflow.com/questions/57562160/angular-notification-not-showing-native-popup-asking-permission) If you encounter any such issue or have any idea on the same, it would be very much helpful.
Thank you for your response again.

**Comment by alcfeoh** [comment]
Yeah, I've seen that before (the SW not re-registering) and it might be a
bug with Chrome. One workaround I've seen is people using incognito mode so
they get a new SW no matter what.

*Alain Chautard*
Google Developer Expert in Angular
Consultant and trainer at angulartraining.com - Interstate 21, LLC

al@interstate21.com
www.interstate21.com
12059 Quail Falls Way
Rancho Cordova, CA 95742
(408) 910-6087


ᐧ

**Comment by alcfeoh** [comment]
Closing because it's not code related, more likely a Chrome issue.

**Comment by jishnunbhattathiri** [comment]
Thanks for your insights
